version: "3.3"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        - PORT=4000
    container_name: graphql-api
    depends_on:
      - mysql
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app:ro
    networks:
      - nginxproxymanager_nginx-proxy-manager-network

  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_DATABASE: movies
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - nginxproxymanager_nginx-proxy-manager-network

volumes:
  db-data: {}
networks:
  nginxproxymanager_nginx-proxy-manager-network:
    external: true